
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // CLI operations (migrate/seed) need a direct, non-pooled connection —
    // Supabase's transaction-mode pooler (DATABASE_URL) doesn't support the
    // session-level advisory locks the migration engine needs, and hangs
    // instead of failing fast. The generated Client still uses DATABASE_URL
    // at runtime via schema.prisma's own datasource block.
    url: env("DIRECT_URL"),
  },
});
